// <auto-generated />
namespace FlashCodeNFe.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TransportadorEnderecoCascade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransportadorEnderecoCascade));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251805349_TransportadorEnderecoCascade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
